# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inicio
other: Nosotros
email: federico.romero91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola! Bienvenido/a a mi sitio Web. Mi nombre es Federico, soy técnico
  electrónico y estudiante de Ingeniería en Informática. Tengo conocimientos
  en algunos lenguajes de programación tales como C, C++, Arduino, Python,
  JavaScript, HTML y CSS. Cualquier duda o consulta no dudes en contactarme.
  Saludos!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blogdefederomero91.com" # the base hostname & protocol for your site
github_username:  frgen

# Build settings
markdown: kramdown
